language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
before_install:
  - npm install -g npm@latest
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8b150eaf525c280ec2ac
    on_success: change
    on_failure: always
    on_start: never
